export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_FAILED = 'FETCH_CONTACTS_FAILED';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';

export const STORE_CONTACT = 'STORE_CONTACT';
export const STORE_CONTACT_FAILED = 'STORE_CONTACT_FAILED';
export const STORE_CONTACT_SUCCESS = 'STORE_CONTACT_SUCCESS';

export const RESET_STATE = 'RESET_STATE';
